"""Falsification tests: does the code+results+plots *suffice* to prove the claim?

Generated by falsification audit 2026-04-20.
Claim: "we have the code, the results, and the plots to prove that
this works, why this works, and how this works."

Two soft falsifications (SF-1, SF-2) were identified and resolved on
2026-04-20 by adding a constructor-comparison table to §6 and a
misspecification-bias table to §7.
"""

from __future__ import annotations

import numpy as np
import pytest

from cramer_distance.demo import run_demo
from cramer_distance.fuzzy_crps import fuzzy_crps, empirical_cdf_from_samples
from cramer_distance.observation_uncertainty import f_obs_from_bounds
from cramer_distance.propriety import verify_propriety_in_expectation


# ---------------------------------------------------------------------------
# SF-1  Constructor coverage gap (soft falsification from P4)
#
# The paper presents three F_obs constructors as contributions but only
# demonstrates ranking reversal with Constructor 2 (parametric). The
# demonstration section must show the reversal holds with Constructor 1
# (bounds-based) for realistic UCDP-style bounds, AND must show it
# disappears for narrow bounds — otherwise the paper claims generality
# it hasn't earned.
# ---------------------------------------------------------------------------

class TestConstructorCoverageGap:
    """The paper must demonstrate ranking reversal with more than one constructor."""

    def test_demonstration_covers_bounds_constructor(self) -> None:
        """§6 must include a demonstration using f_obs_from_bounds.

        SF-1 resolved 2026-04-20: Constructor-comparison table added to §6.
        """
        from pathlib import Path

        demo_tex = Path(__file__).resolve().parents[1] / (
            "paper/sections/06_results.tex"
        )
        text = demo_tex.read_text()
        # The section should reference Constructor 1 / bounds-based F_obs
        assert "Constructor" in text and "bounds" in text.lower(), (
            "§6 demonstrates only Constructor 2 (parametric). "
            "Constructor 1 (bounds) is presented as a contribution in §4 "
            "but never demonstrated. A PNAS reviewer will ask."
        )

    def test_bounds_reversal_holds_for_wide_bounds(self) -> None:
        """Verify ranking reversal works with bounds constructor (wide bounds)."""
        rng = np.random.default_rng(0)
        y = 50.0
        tight = np.exp(rng.normal(np.log(y), 0.05, 4000))
        honest = np.exp(rng.normal(np.log(y), 0.4, 4000))

        f_obs = f_obs_from_bounds(low=25, best=y, high=100)
        tight_pred = empirical_cdf_from_samples(tight)
        honest_pred = empirical_cdf_from_samples(honest)
        grid_max = float(max(np.max(tight), np.max(honest), 200))

        tf = fuzzy_crps(tight_pred, f_obs, grid_min=0.0, grid_max=grid_max, grid_n=4001)
        hf = fuzzy_crps(honest_pred, f_obs, grid_min=0.0, grid_max=grid_max, grid_n=4001)
        assert hf < tf, (
            f"Ranking reversal should hold with wide bounds [25,50,100]: "
            f"tight={tf:.4f}, honest={hf:.4f}"
        )

    def test_bounds_reversal_disappears_for_narrow_bounds(self) -> None:
        """Narrow bounds → no reversal (tight forecaster should win)."""
        rng = np.random.default_rng(0)
        y = 50.0
        tight = np.exp(rng.normal(np.log(y), 0.05, 4000))
        honest = np.exp(rng.normal(np.log(y), 0.4, 4000))

        f_obs = f_obs_from_bounds(low=45, best=y, high=55)
        tight_pred = empirical_cdf_from_samples(tight)
        honest_pred = empirical_cdf_from_samples(honest)
        grid_max = float(max(np.max(tight), np.max(honest), 110))

        tf = fuzzy_crps(tight_pred, f_obs, grid_min=0.0, grid_max=grid_max, grid_n=4001)
        hf = fuzzy_crps(honest_pred, f_obs, grid_min=0.0, grid_max=grid_max, grid_n=4001)
        assert tf < hf, (
            f"Narrow bounds [45,50,55] should NOT reverse ranking: "
            f"tight={tf:.4f}, honest={hf:.4f}"
        )


# ---------------------------------------------------------------------------
# SF-2  Misspecification bias unquantified (soft falsification from P5)
#
# The paper claims consistency and mentions sensitivity to F_obs
# mis-specification in §7, but never quantifies the bias. The audit
# found: at 3.3x overestimation of obs_sigma_rel, the argmin shifts
# by 0.15 (15% of sweep range). This is a gap in the "proves why
# this works" part of the claim.
# ---------------------------------------------------------------------------

class TestMisspecificationBiasUnquantified:
    """The paper must quantify sensitivity to F_obs mis-specification."""

    def test_discussion_quantifies_misspecification_bias(self) -> None:
        """§6 must contain a *numerical* characterisation of the bias.

        SF-2 resolved 2026-04-20: Misspecification-bias table added to §7.
        Moved to §6 (Results) in D-07 restructuring 2026-05-23.
        """
        import re
        from pathlib import Path

        results_tex = Path(__file__).resolve().parents[1] / (
            "paper/sections/06_results.tex"
        )
        text = results_tex.read_text()
        sensitivity_para = text.split("Sensitivity")[1] if "Sensitivity" in text else ""
        # Must contain at least one concrete numerical result like
        # "0.05", "0.15", "15%", a table, or a figure reference
        has_quantitative = bool(re.search(
            r"\b\d+\.\d+\b|\\begin\{tabular\}|\\ref\{fig:.*sensit",
            sensitivity_para,
        ))
        assert has_quantitative, (
            "§7 'Sensitivity to F_obs mis-specification' paragraph discusses "
            "bias qualitatively but provides no concrete numbers, table, or "
            "figure. Audit result: at 3.3x overestimation (obs_sigma_rel=1.0 "
            "vs true_sigma=0.3), argmin shifts by +0.15."
        )

    def test_well_specified_consistency_holds(self) -> None:
        """Baseline: well-specified F_obs → argmin at true_mu."""
        _, _, argmin = verify_propriety_in_expectation(
            true_mu=1.0, true_sigma=0.3, obs_sigma_rel=0.3,
            n_draws=200, seed=42,
        )
        assert abs(argmin - 1.0) < 0.06, (
            f"Well-specified case: argmin={argmin:.4f}, expected ~1.0"
        )

    def test_moderate_misspecification_bias_is_small(self) -> None:
        """2x overestimation should produce bias < 0.1."""
        _, _, argmin = verify_propriety_in_expectation(
            true_mu=1.0, true_sigma=0.3, obs_sigma_rel=0.6,
            n_draws=200, seed=42,
        )
        bias = abs(argmin - 1.0)
        assert bias < 0.10, (
            f"2x overestimation: argmin={argmin:.4f}, bias={bias:.4f}. "
            f"Bias should be small for moderate misspecification."
        )

    def test_severe_misspecification_bias_direction(self) -> None:
        """3.3x overestimation shifts argmin rightward (positive bias)."""
        _, _, argmin = verify_propriety_in_expectation(
            true_mu=1.0, true_sigma=0.3, obs_sigma_rel=1.0,
            n_draws=200, seed=42,
        )
        bias = argmin - 1.0
        assert bias > 0, (
            f"Severe overestimation should bias rightward: argmin={argmin:.4f}"
        )
        assert bias < 0.30, (
            f"Bias should be bounded even at 3.3x: bias={bias:.4f}"
        )


# ---------------------------------------------------------------------------
# OBS-1  Robustness to honest_sigma misspecification (observation from P3)
#
# NOT a falsification — this observation STRENGTHENS the paper but is
# unmentioned. The honest forecaster wins for honest_sigma in [0.10, 0.88]
# when relative_sigma=0.4. The paper should present this as evidence the
# result is not circular.
# ---------------------------------------------------------------------------

class TestHonestSigmaRobustness:
    """The ranking reversal is robust to honest_sigma misspecification."""

    @pytest.mark.parametrize("honest_sigma", [0.10, 0.20, 0.30, 0.50, 0.60, 0.70])
    def test_reversal_robust_to_honest_sigma(self, honest_sigma: float) -> None:
        """Reversal holds even when honest_sigma != relative_sigma."""
        r = run_demo(
            y=50.0, relative_sigma=0.4, tight_sigma=0.05,
            honest_sigma=honest_sigma, n_samples=4000, seed=0,
        )
        assert r.is_ranking_reversal, (
            f"honest_sigma={honest_sigma}: classical_winner={r.classical_winner}, "
            f"fuzzy_winner={r.fuzzy_winner}. Expected reversal."
        )

    def test_reversal_eventually_fails_for_very_wide_honest(self) -> None:
        """Reversal disappears when honest forecaster is absurdly wide."""
        r = run_demo(
            y=50.0, relative_sigma=0.4, tight_sigma=0.05,
            honest_sigma=1.0, n_samples=4000, seed=0,
        )
        assert not r.is_ranking_reversal, (
            f"honest_sigma=1.0 should be too wide to beat tight: "
            f"tight_f={r.tight_fuzzy:.4f}, honest_f={r.honest_fuzzy:.4f}"
        )
