"""Falsification tests: is the fuzzy CRPS proposal original research?

Generated by falsification audit 2026-04-20.
Claim: "this is original research and has not already been done in
other fields where input uncertainty is normal."

Three soft falsifications identified and resolved on 2026-04-20:
  SF-1: Bröcker & Smith (2007) not cited — resolved by adding citation
        and positioning paragraph in §7.
  SF-2: Thorarinsdottir et al. (2013) IQD = identical mathematical
        object — resolved by naming IQD explicitly in §4.
  SF-3: Three papers on CRPS + observation uncertainty not cited
        — resolved by adding Bessac & Naveau 2021, Bolin & Wallin 2023,
        Weijs et al. 2011 to refs.bib and citing in §1, §4, §7.
"""

from __future__ import annotations

import re
from pathlib import Path

REFS_BIB = Path(__file__).resolve().parents[1] / "paper/refs.bib"
INTRO_TEX = Path(__file__).resolve().parents[1] / "paper/sections/01_introduction.tex"
METHOD_TEX = Path(__file__).resolve().parents[1] / "paper/sections/04_fuzzy_crps.tex"
DISCUSSION_TEX = Path(__file__).resolve().parents[1] / "paper/sections/07_discussion.tex"


# ---------------------------------------------------------------------------
# SF-1  Bröcker & Smith (2007) not cited
#
# Bröcker & Smith (2007) propose scoring forecasts under observation
# error via E[S(F, Y)|obs] — conditional expectation of the score over
# the error distribution. This is the closest prior framework to
# fuzzy CRPS and must be cited and positioned against.
# ---------------------------------------------------------------------------

class TestBrockerSmithCitation:
    """The paper must cite Bröcker & Smith (2007) on scoring under observation error."""

    def test_bibliography_includes_brocker_smith_2007(self) -> None:
        """SF-1 resolved 2026-04-20: Bröcker & Smith (2007) added to refs.bib."""
        bib = REFS_BIB.read_text()
        assert re.search(r"brocker.*2007|bröcker.*2007|broecker.*2007", bib, re.IGNORECASE), (
            "refs.bib does not contain Bröcker & Smith (2007). Their conditional-"
            "expectation framework for scoring under observation error is the "
            "closest prior art and must be cited."
        )

    def test_discussion_positions_against_brocker_smith(self) -> None:
        """SF-1 resolved 2026-04-20: §7 positioning paragraph added."""
        text = DISCUSSION_TEX.read_text()
        has_ref = bool(re.search(
            r"Br[öo]cker|conditional.expectation.*scor|E\[S\(F",
            text,
        ))
        assert has_ref, (
            "§7 does not discuss Bröcker & Smith (2007) conditional-expectation "
            "approach. The paper must explain how direct F_obs substitution "
            "differs from taking E[S(F, Y)|obs]."
        )


# ---------------------------------------------------------------------------
# SF-2  Thorarinsdottir (2013) IQD insufficiently acknowledged
#
# Thorarinsdottir et al. (2013) define the IQD = ∫(F-G)² dz between
# two non-degenerate distributions and use it for climate model
# evaluation. This IS fuzzy CRPS. The paper cites them but does not
# explicitly state the mathematical identity.
# ---------------------------------------------------------------------------

class TestThorarinsdottirAcknowledgement:
    """The paper must explicitly state that Thorarinsdottir IQD is the same object."""

    def test_method_section_states_iqd_identity(self) -> None:
        """SF-2 resolved 2026-04-20: IQD named explicitly in §4."""
        text = METHOD_TEX.read_text()
        has_iqd = bool(re.search(
            r"[Ii]ntegrated\s+[Qq]uadratic\s+[Dd]istance|IQD",
            text,
        ))
        assert has_iqd, (
            "§4 does not mention the Integrated Quadratic Distance (IQD) by "
            "name. Thorarinsdottir et al. (2013) define the IQD as ∫(F-G)²dz "
            "— mathematically identical to Eq. 1. The paper must state this "
            "identity explicitly to pre-empt reviewer objections."
        )


# ---------------------------------------------------------------------------
# SF-3  Missing citations: post-2020 observation-uncertainty literature
#
# Three recent papers address CRPS under observation uncertainty and
# are not cited:
#   - Bessac & Naveau (2021): hidden-variable CRPS under obs error
#   - Bolin & Wallin (2023): scaled CRPS for varying obs uncertainty
#   - Weijs, van Nooijen & van de Giesen (2011): information-theoretic
#     framework for obs uncertainty in verification
# ---------------------------------------------------------------------------

class TestRecentLiteratureCoverage:
    """The bibliography must cover recent work on CRPS + observation uncertainty."""

    def test_cites_bessac_naveau_2021(self) -> None:
        """SF-3 resolved 2026-04-20: Bessac & Naveau (2021) added."""
        bib = REFS_BIB.read_text()
        assert re.search(r"bessac.*2021|naveau.*2021.*imperfect", bib, re.IGNORECASE), (
            "refs.bib does not cite Bessac & Naveau (2021) 'Forecast score "
            "distributions with imperfect observations'. They derive CRPS "
            "behaviour under Gaussian and Gamma observation error — directly "
            "relevant prior art."
        )

    def test_cites_bolin_wallin_2023(self) -> None:
        """SF-3 resolved 2026-04-20: Bolin & Wallin (2023) added."""
        bib = REFS_BIB.read_text()
        assert re.search(r"bolin.*2023|wallin.*2023.*scoring", bib, re.IGNORECASE), (
            "refs.bib does not cite Bolin & Wallin (2023) 'Local scale "
            "invariance and robustness of proper scoring rules'. They show "
            "CRPS overweights observations with large uncertainty."
        )

    def test_cites_weijs_2011(self) -> None:
        """SF-3 resolved 2026-04-20: Weijs et al. (2011) added."""
        bib = REFS_BIB.read_text()
        assert re.search(r"weijs.*2011|observational.*uncertainty.*verification", bib, re.IGNORECASE), (
            "refs.bib does not cite Weijs, van Nooijen & van de Giesen (2011) "
            "'Accounting for Observational Uncertainty in Forecast Verification'."
        )
